version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    groups:
      npm-dependencies:
        patterns: ["*"]

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
    groups:
      docker-images:
        patterns: ["*"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns: ["*"]
